image: gitpod/workspace-full

tasks:
  - init: |
      composer create-project --prefer-dist laravel/laravel .
      cd laravel
      cp .env.example .env
      php artisan key:generate
      docker-compose up -d
  - command: |
      docker-compose exec app php artisan migrate

ports:
  - port: 8000
    onOpen: open-preview
