image: gitpod/workspace-full

tasks:
  - init: |
      composer create-project --prefer-dist laravel/laravel .
      docker-compose up -d
  - command: |
      docker-compose exec app php artisan serve --host=0.0.0.0 --port=8000

ports:
  - port: 8000
    onOpen: open-preview
