image: gitpod/workspace-full

tasks:
  - init: |
      composer create-project --prefer-dist laravel/laravel .
      cd laravel  # Change directory to Laravel project
      php artisan key:generate  # Generate application key
      npm install && npm run dev  # Install frontend dependencies and compile assets
      docker-compose up -d

  - command: |
      docker-compose exec app php artisan serve --host=0.0.0.0 --port=8000

ports:
  - port: 8000
    onOpen: open-preview
