version: '3.8'

services:
  app:
    image: laravelsail/php82-composer
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

